"use client";

import AdminSidebar from "@/components/admin/AdminSidebar";
import AdminTopbar from "@/components/admin/AdminTopbar";
import { showAuthToast } from "@/components/AuthToast";
import { useEffect, useState } from "react";
import "../products/new/new-product.css";
import "../admin-functional.css";

type Settings={storeName:string;supportEmail:string;supportPhone:string;currency:string;storeStatus:string;orderNotifications:boolean;promoEnabled:boolean;promoText:string;promoCode:string};
const defaults:Settings={storeName:"Eye Champ",supportEmail:"support@eyechamp.com",supportPhone:"",currency:"PKR",storeStatus:"Live",orderNotifications:true,promoEnabled:true,promoText:"Buy one, get one 20% off.",promoCode:"GET20"};

export default function SettingsPage(){
  const [menuOpen,setMenuOpen]=useState(false),[settings,setSettings]=useState<Settings>(defaults),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  const [account,setAccount]=useState({email:"",currentPassword:"",newPassword:"",confirmPassword:""}),[accountSaving,setAccountSaving]=useState(false);
  useEffect(()=>{Promise.all([
    fetch("/api/admin/settings",{credentials:"include",cache:"no-store"}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not load settings.");setSettings({...defaults,...result.settings})}),
    fetch("/api/admin/session",{credentials:"include",cache:"no-store"}).then(async response=>{const result=await response.json();if(response.ok&&result.admin)setAccount(current=>({...current,email:result.admin.email||""}))}),
  ]).catch(error=>showAuthToast({message:error instanceof Error?error.message:"Could not load settings.",type:"error"})).finally(()=>setLoading(false))},[]);
  const save=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);try{const response=await fetch("/api/admin/settings",{method:"PUT",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not save settings.");setSettings({...defaults,...result.settings});showAuthToast({message:"Settings saved.",type:"success"})}catch(error){showAuthToast({message:error instanceof Error?error.message:"Could not save settings.",type:"error"})}finally{setSaving(false)}};
  const saveAccount=async(event:React.FormEvent)=>{event.preventDefault();setAccountSaving(true);try{const response=await fetch("/api/admin/settings/account",{method:"PUT",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(account)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not update admin login.");setAccount({email:result.admin.email,currentPassword:"",newPassword:"",confirmPassword:""});showAuthToast({message:"Admin login updated.",type:"success"})}catch(error){showAuthToast({message:error instanceof Error?error.message:"Could not update admin login.",type:"error"})}finally{setAccountSaving(false)}};
  return <main className="np-admin"><AdminSidebar open={menuOpen} onClose={()=>setMenuOpen(false)}/><section className="np-workspace"><AdminTopbar onMenuOpen={()=>setMenuOpen(true)}/><div className="admin-functional-content">
    <header className="admin-functional-head"><div><p>Management</p><h1>Settings</h1><span>Control store preferences, account settings, and admin configuration.</span></div></header>
    <section className="admin-functional-summary"><article><span>Store status</span><strong>{settings.storeStatus}</strong><small>Current storefront state</small></article><article><span>Currency</span><strong>{settings.currency}</strong><small>Displayed in admin totals</small></article><article><span>Notifications</span><strong>{settings.orderNotifications?"On":"Off"}</strong><small>Order alerts</small></article></section>
    <section className="admin-functional-grid"><article className="admin-functional-card"><h2>Store settings</h2>{loading?<div className="admin-functional-empty">Loading settings...</div>:<form className="admin-functional-form" onSubmit={save}><label>Store name<input value={settings.storeName} onChange={event=>setSettings({...settings,storeName:event.target.value})} required/></label><label>Support email<input type="email" value={settings.supportEmail} onChange={event=>setSettings({...settings,supportEmail:event.target.value})} required/></label><label>Support phone<input value={settings.supportPhone} onChange={event=>setSettings({...settings,supportPhone:event.target.value})}/></label><label>Currency<input value={settings.currency} onChange={event=>setSettings({...settings,currency:event.target.value})} required/></label><label>Store status<select value={settings.storeStatus} onChange={event=>setSettings({...settings,storeStatus:event.target.value})}><option>Live</option><option>Paused</option></select></label><label>Order notifications<select value={settings.orderNotifications?"On":"Off"} onChange={event=>setSettings({...settings,orderNotifications:event.target.value==="On"})}><option>On</option><option>Off</option></select></label><button disabled={saving}>{saving?"Saving...":"Save settings"}</button></form>}</article>
    <article className="admin-functional-card"><h2>Top announcement bar</h2>{loading?<div className="admin-functional-empty">Loading announcement...</div>:<form className="admin-functional-form" onSubmit={save}><label>Show announcement<select value={settings.promoEnabled?"Yes":"No"} onChange={event=>setSettings({...settings,promoEnabled:event.target.value==="Yes"})}><option>Yes</option><option>No</option></select></label><label>Message<input value={settings.promoText} onChange={event=>setSettings({...settings,promoText:event.target.value})} maxLength={200} placeholder="Buy one, get one 20% off." /></label><label>Promo code<input value={settings.promoCode} onChange={event=>setSettings({...settings,promoCode:event.target.value})} maxLength={40} placeholder="GET20" /></label><button disabled={saving}>{saving?"Saving...":"Save announcement"}</button></form>}</article>
    <article className="admin-functional-card"><h2>Admin login</h2>{loading?<div className="admin-functional-empty">Loading account...</div>:<form className="admin-functional-form" onSubmit={saveAccount}><label>Email address<input type="email" value={account.email} onChange={event=>setAccount({...account,email:event.target.value})} required/></label><label>Current password<input type="password" value={account.currentPassword} onChange={event=>setAccount({...account,currentPassword:event.target.value})} autoComplete="current-password" required/></label><label>New password<input type="password" value={account.newPassword} onChange={event=>setAccount({...account,newPassword:event.target.value})} autoComplete="new-password" placeholder="Leave blank to keep current password"/></label><label>Confirm new password<input type="password" value={account.confirmPassword} onChange={event=>setAccount({...account,confirmPassword:event.target.value})} autoComplete="new-password" placeholder="Leave blank to keep current password"/></label><button disabled={accountSaving}>{accountSaving?"Updating...":"Update admin login"}</button></form>}</article>
    <article className="admin-functional-card"><h2>Saved configuration</h2><div className="admin-finance-list"><div><strong>{settings.storeName}</strong><span>Store name</span></div><div><strong>{settings.supportEmail}</strong><span>Support email</span></div><div><strong>{settings.supportPhone||"No phone set"}</strong><span>Support phone</span></div><div><strong><span className={`admin-functional-badge ${settings.storeStatus.toLowerCase()}`}>{settings.storeStatus}</span></strong><span>Store visibility</span></div></div></article>
    </section>
  </div></section></main>
}
