"use client";

import AdminSidebar from "@/components/admin/AdminSidebar";
import AdminTopbar from "@/components/admin/AdminTopbar";
import { showAuthToast } from "@/components/AuthToast";
import { useEffect, useState } from "react";
import "../products/new/new-product.css";
import "../admin-functional.css";

type Method={id:string;name:string;zone:string;price:number;estimatedDays:string;active:boolean};
const money=(value:number)=>`Rs ${Number(value||0).toLocaleString("en-PK",{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function ShippingPage(){
  const [menuOpen,setMenuOpen]=useState(false),[methods,setMethods]=useState<Method[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  const [form,setForm]=useState({name:"",zone:"Pakistan",price:"",estimatedDays:"3-5 business days",active:true});
  const load=()=>fetch("/api/admin/shipping",{credentials:"include",cache:"no-store"}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not load shipping.");setMethods(result.methods??[])});
  useEffect(()=>{load().catch(error=>showAuthToast({message:error instanceof Error?error.message:"Could not load shipping.",type:"error"})).finally(()=>setLoading(false))},[]);
  const create=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);try{const response=await fetch("/api/admin/shipping",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not create shipping method.");setMethods(current=>[result.method,...current]);setForm({name:"",zone:"Pakistan",price:"",estimatedDays:"3-5 business days",active:true});showAuthToast({message:"Shipping method created.",type:"success"})}catch(error){showAuthToast({message:error instanceof Error?error.message:"Could not create shipping method.",type:"error"})}finally{setSaving(false)}};
  const toggle=async(method:Method)=>{const response=await fetch(`/api/admin/shipping/${method.id}`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({active:!method.active})});const result=await response.json();if(!response.ok)return showAuthToast({message:result.error||"Could not update shipping method.",type:"error"});setMethods(current=>current.map(item=>item.id===method.id?{...item,active:result.method.active}:item));showAuthToast({message:"Shipping method updated.",type:"success"})};
  const remove=async(id:string)=>{const response=await fetch(`/api/admin/shipping/${id}`,{method:"DELETE",credentials:"include"});if(!response.ok)return showAuthToast({message:"Could not delete shipping method.",type:"error"});setMethods(current=>current.filter(item=>item.id!==id));showAuthToast({message:"Shipping method deleted.",type:"success"})};
  return <main className="np-admin"><AdminSidebar open={menuOpen} onClose={()=>setMenuOpen(false)}/><section className="np-workspace"><AdminTopbar onMenuOpen={()=>setMenuOpen(true)}/><div className="admin-functional-content">
    <header className="admin-functional-head"><div><p>Management</p><h1>Shipping</h1><span>Manage delivery zones, fulfillment settings, and shipping methods.</span></div></header>
    <section className="admin-functional-summary"><article><span>Shipping zones</span><strong>{new Set(methods.map(item=>item.zone)).size}</strong><small>Configured delivery areas</small></article><article><span>Active methods</span><strong>{methods.filter(item=>item.active).length}</strong><small>Available at checkout</small></article><article><span>Inactive methods</span><strong>{methods.filter(item=>!item.active).length}</strong><small>Hidden from customers</small></article></section>
    <section className="admin-functional-grid"><article className="admin-functional-card"><h2>Create shipping method</h2><form className="admin-functional-form" onSubmit={create}><label>Name<input value={form.name} onChange={event=>setForm({...form,name:event.target.value})} placeholder="Standard delivery" required/></label><label>Zone<input value={form.zone} onChange={event=>setForm({...form,zone:event.target.value})} required/></label><label>Price<input type="number" min="0" step="0.01" value={form.price} onChange={event=>setForm({...form,price:event.target.value})} required/></label><label>Estimated days<input value={form.estimatedDays} onChange={event=>setForm({...form,estimatedDays:event.target.value})} required/></label><label>Status<select value={form.active?"Active":"Inactive"} onChange={event=>setForm({...form,active:event.target.value==="Active"})}><option>Active</option><option>Inactive</option></select></label><button disabled={saving}>{saving?"Saving...":"Create method"}</button></form></article>
    <article className="admin-functional-card"><h2>Shipping methods</h2>{loading?<div className="admin-functional-empty">Loading shipping methods...</div>:<div className="admin-functional-table"><table><thead><tr><th>Name</th><th>Zone</th><th>Price</th><th>Estimate</th><th>Status</th><th/></tr></thead><tbody>{methods.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.zone}</td><td>{money(item.price)}</td><td>{item.estimatedDays}</td><td><span className={`admin-functional-badge ${item.active?"active":"draft"}`}>{item.active?"Active":"Inactive"}</span></td><td><button onClick={()=>toggle(item)}>{item.active?"Disable":"Enable"}</button><button className="danger" onClick={()=>remove(item.id)}>Delete</button></td></tr>)}</tbody></table></div>}{!loading&&!methods.length&&<div className="admin-functional-empty">No shipping methods created yet.</div>}</article></section>
  </div></section></main>
}
