"use client";

import AdminSidebar from "@/components/admin/AdminSidebar";
import AdminTopbar from "@/components/admin/AdminTopbar";
import { showAuthToast } from "@/components/AuthToast";
import { useEffect, useState } from "react";
import "../products/new/new-product.css";
import "../admin-functional.css";

type Discount={id:string;code:string;type:string;value:number;status:string;usageLimit:number|null;createdAt:string};
const money=(value:number)=>`Rs ${Number(value||0).toLocaleString("en-PK",{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function DiscountsPage(){
  const [menuOpen,setMenuOpen]=useState(false),[discounts,setDiscounts]=useState<Discount[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  const [form,setForm]=useState({code:"",type:"Percentage",value:"",status:"Active",usageLimit:""});
  const load=()=>fetch("/api/admin/discounts",{credentials:"include",cache:"no-store"}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not load discounts.");setDiscounts(result.discounts??[])});
  useEffect(()=>{load().catch(error=>showAuthToast({message:error instanceof Error?error.message:"Could not load discounts.",type:"error"})).finally(()=>setLoading(false))},[]);
  const create=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);try{const response=await fetch("/api/admin/discounts",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not create discount.");setDiscounts(current=>[result.discount,...current]);setForm({code:"",type:"Percentage",value:"",status:"Active",usageLimit:""});showAuthToast({message:"Discount created.",type:"success"})}catch(error){showAuthToast({message:error instanceof Error?error.message:"Could not create discount.",type:"error"})}finally{setSaving(false)}};
  const setStatus=async(id:string,status:string)=>{const response=await fetch(`/api/admin/discounts/${id}`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});const result=await response.json();if(!response.ok)return showAuthToast({message:result.error||"Could not update discount.",type:"error"});setDiscounts(current=>current.map(item=>item.id===id?{...item,status}:item));showAuthToast({message:"Discount updated.",type:"success"})};
  const remove=async(id:string)=>{const response=await fetch(`/api/admin/discounts/${id}`,{method:"DELETE",credentials:"include"});if(!response.ok)return showAuthToast({message:"Could not delete discount.",type:"error"});setDiscounts(current=>current.filter(item=>item.id!==id));showAuthToast({message:"Discount deleted.",type:"success"})};
  return <main className="np-admin"><AdminSidebar open={menuOpen} onClose={()=>setMenuOpen(false)}/><section className="np-workspace"><AdminTopbar onMenuOpen={()=>setMenuOpen(true)}/><div className="admin-functional-content">
    <header className="admin-functional-head"><div><p>Sales</p><h1>Discounts</h1><span>Create and manage promotional offers for your store.</span></div></header>
    <section className="admin-functional-summary"><article><span>Active discounts</span><strong>{discounts.filter(item=>item.status==="Active").length}</strong><small>Currently available</small></article><article><span>Draft</span><strong>{discounts.filter(item=>item.status==="Draft").length}</strong><small>Not visible yet</small></article><article><span>Expired</span><strong>{discounts.filter(item=>item.status==="Expired").length}</strong><small>Past campaigns</small></article></section>
    <section className="admin-functional-grid"><article className="admin-functional-card"><h2>Create discount</h2><form className="admin-functional-form" onSubmit={create}><label>Code<input value={form.code} onChange={event=>setForm({...form,code:event.target.value})} placeholder="SUMMER10" required/></label><label>Type<select value={form.type} onChange={event=>setForm({...form,type:event.target.value})}><option>Percentage</option><option>Fixed amount</option></select></label><label>Value<input type="number" min="0" step="0.01" value={form.value} onChange={event=>setForm({...form,value:event.target.value})} required/></label><label>Status<select value={form.status} onChange={event=>setForm({...form,status:event.target.value})}><option>Active</option><option>Draft</option><option>Expired</option></select></label><label>Usage limit<input type="number" min="0" value={form.usageLimit} onChange={event=>setForm({...form,usageLimit:event.target.value})} placeholder="Optional"/></label><button disabled={saving}>{saving?"Saving...":"Create discount"}</button></form></article>
    <article className="admin-functional-card"><h2>Discount codes</h2>{loading?<div className="admin-functional-empty">Loading discounts...</div>:<div className="admin-functional-table"><table><thead><tr><th>Code</th><th>Value</th><th>Status</th><th>Limit</th><th/></tr></thead><tbody>{discounts.map(item=><tr key={item.id}><td><strong>{item.code}</strong></td><td>{item.type==="Percentage"?`${item.value}%`:money(item.value)}</td><td><span className={`admin-functional-badge ${item.status.toLowerCase()}`}>{item.status}</span></td><td>{item.usageLimit??"No limit"}</td><td><button onClick={()=>setStatus(item.id,item.status==="Active"?"Draft":"Active")}>{item.status==="Active"?"Disable":"Activate"}</button><button className="danger" onClick={()=>remove(item.id)}>Delete</button></td></tr>)}</tbody></table></div>}{!loading&&!discounts.length&&<div className="admin-functional-empty">No discounts created yet.</div>}</article></section>
  </div></section></main>
}
