"use client";
import { ArrowRight } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, KeyboardEvent, useRef, useState, type ClipboardEvent } from "react";
import "./login.css";
import "./otp.css";

export default function CustomerLoginPage(){
 const router=useRouter(),[email,setEmail]=useState(""),[challengeId,setChallengeId]=useState(""),[digits,setDigits]=useState(["","","","","",""]),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);const inputs=useRef<Array<HTMLInputElement|null>>([]);
 async function requestCode(event?:FormEvent<HTMLFormElement>){event?.preventDefault();setMessage("");setLoading(true);try{const response=await fetch("/api/customer-auth/request-otp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})}),result=await response.json();if(!response.ok)throw new Error(result.error||"Unable to send verification code.");setChallengeId(result.challengeId);setDigits(["","","","","",""]);setTimeout(()=>inputs.current[0]?.focus(),0)}catch(error){setMessage(error instanceof Error?error.message:"Unable to send verification code.")}finally{setLoading(false)}}
 async function verify(code:string){if(code.length!==6||loading)return;setMessage("");setLoading(true);try{const response=await fetch("/api/customer-auth/verify-otp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({challengeId,code})}),result=await response.json();if(!response.ok)throw new Error(result.error||"Unable to verify code.");router.replace("/profile");router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"Unable to verify code.")}finally{setLoading(false)}}
 function changeDigit(index:number,value:string){const clean=value.replace(/\D/g,"").slice(-1),next=[...digits];next[index]=clean;setDigits(next);if(clean&&index<5)inputs.current[index+1]?.focus();if(next.every(Boolean))verify(next.join(""))}function keyDown(index:number,event:KeyboardEvent<HTMLInputElement>){if(event.key==="Backspace"&&!digits[index]&&index>0)inputs.current[index-1]?.focus()}function paste(event:ClipboardEvent<HTMLInputElement>){const code=event.clipboardData.getData("text").replace(/\D/g,"").slice(0,6);if(code.length===6){event.preventDefault();setDigits(code.split(""));verify(code)}}
 return <main className="customer-login"><Link className="customer-login-logo" href="/" aria-label="Eye Champ home"><Image src="/images/logo.png" alt="Eye Champ" width={170} height={52} priority/></Link><section className="customer-login-panel">{!challengeId?<><h1>Sign in</h1><p>Enter the email used to place your order and we&apos;ll send you a verification code</p><form onSubmit={requestCode} noValidate><label><span className="sr-only">Email</span><input type="email" value={email} onChange={event=>{setEmail(event.target.value);setMessage("")}} placeholder="Email" autoComplete="email"/><button type="submit" disabled={loading} aria-label="Send code"><ArrowRight/></button></label><label className="customer-login-offers"><input type="checkbox"/><span>Email me with news and offers</span></label></form><small>By continuing, you agree to our <Link href="/terms-of-use">Terms of service</Link></small></>:<><h1>Enter code</h1><p>Sent to {email}<button className="change-email" onClick={()=>{setChallengeId("");setMessage("")}}>Change</button></p><div className="otp-inputs" aria-label="Six digit verification code">{digits.map((digit,index)=><input key={index} ref={element=>{inputs.current[index]=element}} value={digit} onChange={event=>changeDigit(index,event.target.value)} onKeyDown={event=>keyDown(index,event)} onPaste={paste} inputMode="numeric" autoComplete={index===0?"one-time-code":"off"} maxLength={1} aria-label={`Digit ${index+1}`} disabled={loading}/>)}</div><button className="resend-code" disabled={loading} onClick={()=>requestCode()}>Resend code</button></>}{message&&<p className="customer-login-message" role="alert">{message}</p>}</section><Link className="customer-login-privacy" href="/internet-privacy-policy">Privacy policy</Link></main>;
}
