"use client";

import AdminSidebar from "@/components/admin/AdminSidebar";
import AdminTopbar from "@/components/admin/AdminTopbar";
import DeleteConfirmDialog from "@/components/admin/DeleteConfirmDialog";
import { ArrowLeft, ArrowRight, ArrowUpDown, BadgeCheck, Filter, Globe2, MoreHorizontal, Plus, Search, Star, X } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { showAuthToast } from "@/components/AuthToast";
import "../products/new/new-product.css";
import "./brands.css";

type Brand = { id: string; name: string; slug: string; description: string; products: number; status: "Active" | "Draft"; featured: boolean; origin: string; updated: string };
export default function BrandsPage() {
  const [menuOpen, setMenuOpen] = useState(false), [brands, setBrands] = useState<Brand[]>([]), [query, setQuery] = useState(""), [status, setStatus] = useState("All statuses"), [selected, setSelected] = useState<string[]>([]), [modalOpen, setModalOpen] = useState(false), [name, setName] = useState(""), [origin, setOrigin] = useState("");
  const [deleteConfirmOpen, setDeleteConfirmOpen] = useState(false), [deleting, setDeleting] = useState(false);
  useEffect(() => { fetch("/api/admin/brands", { cache: "no-store" }).then(async response => { const result = await response.json() as { brands?: Brand[]; error?: string }; if (!response.ok) throw new Error(result.error); setBrands(result.brands ?? []) }).catch(() => showAuthToast({ message: "Could not load brands.", type: "error" })) }, []);
  const shown = useMemo(() => brands.filter(brand => (status === "All statuses" || brand.status === status) && (`${brand.name} ${brand.origin}`.toLowerCase().includes(query.toLowerCase()))), [brands, query, status]);
  const toggle = (id: string) => setSelected(value => value.includes(id) ? value.filter(item => item !== id) : [...value, id]);
  async function createBrand(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const clean = name.trim(); if (!clean) return; const form = new FormData(event.currentTarget); try { const response = await fetch("/api/admin/brands", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: clean, origin: origin || "Not specified", description: String(form.get("description") || ""), status: String(form.get("status") || "Draft"), featured: form.get("featured") === "on" }) }); const result = await response.json() as { brand?: Brand; error?: string }; if (!response.ok || !result.brand) throw new Error(result.error || "Could not create brand."); setBrands(value => [result.brand!, ...value]); setName(""); setOrigin(""); setModalOpen(false); showAuthToast({ message: "Brand created successfully.", type: "success" }) } catch (error) { showAuthToast({ message: error instanceof Error ? error.message : "Could not create brand.", type: "error" }) } }
  async function bulkUpdate(change: { status?: "Active" | "Draft"; featured?: boolean }) { const response = await fetch("/api/admin/brands", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ids: selected, ...change }) }); if (!response.ok) return showAuthToast({ message: "Could not update brands.", type: "error" }); setBrands(value => value.map(item => selected.includes(item.id) ? { ...item, ...change, updated: "Just now" } : item)); setSelected([]); showAuthToast({ message: "Brands updated successfully.", type: "success" }) }
  async function bulkDelete() { setDeleting(true); try { const response = await fetch("/api/admin/brands", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ids: selected }) }); if (!response.ok) throw new Error("Could not delete brands."); setBrands(value => value.filter(item => !selected.includes(item.id))); setSelected([]); setDeleteConfirmOpen(false); showAuthToast({ message: "Brands deleted successfully.", type: "success" }) } catch (error) { showAuthToast({ message: error instanceof Error ? error.message : "Could not delete brands.", type: "error" }) } finally { setDeleting(false) } }
  return <main className="np-admin brands-admin">
    <AdminSidebar open={menuOpen} onClose={() => setMenuOpen(false)} />
    <section className="np-workspace"><AdminTopbar onMenuOpen={() => setMenuOpen(true)} />
      <div className="brands-content">
        <div className="brands-head"><div><p>Catalog</p><h1>Brands</h1><span>Manage designer labels and brand storefronts.</span></div><button onClick={() => setModalOpen(true)}><Plus size={17} /> Add brand</button></div>
        <section className="brands-summary"><article><span><BadgeCheck size={17} /></span><div><small>Total brands</small><strong>{brands.length}</strong><p>{brands.filter(item => item.status === "Active").length} currently active</p></div></article><article><span className="gold"><Star size={17} /></span><div><small>Featured brands</small><strong>{brands.filter(item => item.featured).length}</strong><p>Promoted on storefront</p></div></article><article><span className="blue"><Globe2 size={17} /></span><div><small>Countries represented</small><strong>{new Set(brands.map(item => item.origin)).size}</strong><p>Global eyewear partners</p></div></article></section>
        <section className="brands-panel"><div className="brands-tabs"><div><button className="active">All <span>{brands.length}</span></button><button>Active <span>{brands.filter(item => item.status === "Active").length}</span></button><button>Featured <span>{brands.filter(item => item.featured).length}</span></button><button>Draft</button></div><button>Sort: A-Z <ArrowUpDown size={12} /></button></div>
          <div className="brands-tools"><label><Search size={16} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search brands or country" /></label><select value={status} onChange={event => setStatus(event.target.value)}><option>All statuses</option><option>Active</option><option>Draft</option></select><select><option>All origins</option><option>Italy</option><option>France</option><option>Germany</option><option>United States</option></select><button><Filter size={15} /> More filters</button></div>
          {selected.length > 0 && <div className="brands-bulk"><strong>{selected.length} brands selected</strong><button onClick={() => bulkUpdate({ status: "Active" })}>Set active</button><button onClick={() => bulkUpdate({ featured: true })}>Feature</button><button onClick={() => setDeleteConfirmOpen(true)}>Delete</button><button onClick={() => setSelected([])}>Clear</button></div>}
          <div className="brands-table"><table><thead><tr><th><input type="checkbox" checked={shown.length > 0 && selected.length === shown.length} onChange={event => setSelected(event.target.checked ? shown.map(item => item.id) : [])} /></th><th>Brand</th><th>Origin</th><th>Products</th><th>Featured</th><th>Status</th><th>Last updated</th><th /></tr></thead><tbody>{shown.map(brand => <tr key={brand.id}><td><input type="checkbox" checked={selected.includes(brand.id)} onChange={() => toggle(brand.id)} /></td><td><div className="brand-cell"><div><strong>{brand.name}</strong><small>/{brand.slug}</small><p>{brand.description}</p></div></div></td><td>{brand.origin}</td><td><strong>{brand.products}</strong> products</td><td>{brand.featured ? <span className="brand-featured"><Star size={11} /> Featured</span> : <span className="brand-standard">Standard</span>}</td><td><span className={`brand-status ${brand.status.toLowerCase()}`}><i />{brand.status}</span></td><td>{brand.updated}</td><td><button aria-label={`Actions for ${brand.name}`}><MoreHorizontal size={18} /></button></td></tr>)}</tbody></table></div>
          {shown.length === 0 && <div className="brands-empty"><BadgeCheck size={32} /><h2>No brands found</h2><p>Try changing your search or status filter.</p><button onClick={() => { setQuery(""); setStatus("All statuses") }}>Clear filters</button></div>}
          <div className="brands-pagination"><span>Showing {shown.length} of {brands.length} brands</span><div><button disabled aria-label="Previous page"><ArrowLeft size={13} /></button><button className="active">1</button><button disabled aria-label="Next page"><ArrowRight size={13} /></button></div></div>
        </section>
      </div>
    </section>
    {modalOpen && <div className="brand-modal-backdrop" onClick={() => setModalOpen(false)}><section className="brand-modal" onClick={event => event.stopPropagation()}><header><div><h2>Add brand</h2><p>Create a new designer brand storefront.</p></div><button onClick={() => setModalOpen(false)} aria-label="Close"><X size={19} /></button></header><form onSubmit={createBrand}><label>Brand name<input required value={name} onChange={event => setName(event.target.value)} placeholder="e.g. Persol" /></label><div className="brand-form-row"><label>Country of origin<input value={origin} onChange={event => setOrigin(event.target.value)} placeholder="e.g. Italy" /></label><label>Status<select name="status"><option>Draft</option><option>Active</option></select></label></div><label>Description<textarea name="description" placeholder="Describe the brand..." /></label><label className="brand-feature-check"><input name="featured" type="checkbox" /> Feature this brand on the storefront</label><footer><button type="button" onClick={() => setModalOpen(false)}>Cancel</button><button className="save">Add brand</button></footer></form></section></div>}
    <DeleteConfirmDialog open={deleteConfirmOpen} count={selected.length} singular="brand" plural="brands" deleting={deleting} onCancel={() => setDeleteConfirmOpen(false)} onConfirm={bulkDelete} />
  </main>
}
